export default interface IHAEMATOLOGY {
    Print?: boolean,
    Comments?: boolean,
    PrintAll?:boolean,
    HB: string,
    TLC: string,
    Polymorphs: string,
    Lymphocytes: string,
    Monocytes: string,
    Eosinophils: string,
    Basophils: string,
    Description: string,
    AbnormalCell: string,
    ESR: string,
    BGrouping: string,
    RhTyping: string,
    MaterialParasite: string,
    PTIControl: string,
    Test: string,
    Index: string,
    INR: string,
    APTT: string,
    BleedingTime: string,
    ClottingTime: string,
    PTTK: string,
    TotalRBCCount: string,
    Platelets_L: string,
    Platelets_T: string,
    PCV: string,
    Reticulocyte: string,
    MCV: string,
    MCH: string,
    MCHC: string,
    AEosinophilCount: string,
    LECell: string,
    CoombsTest_D: string,
    CoombsTest_I: string,
}